### ISSUE TITLE
Multiple tween doesn't work with variables

### ISSUE THREAD

**Issue by ArysWasTaken** [BjornLuG/LuaTween-for-Rainmeter#1]
`Tween1=Multiple | Variable | opacity%% | 0 | 255 | 80 | 7`

Instead of substituting the %% with a number, the variable is shown in the logs as `opacity%%`.
Otherwise it works fine with SectionNames.

![Rainmeter_2019-09-10_14-44-36](https://user-images.githubusercontent.com/29689804/64619372-e1225b80-d3d9-11e9-9bd0-e31ab9778cd3.png)

**Comment by bluwy** [comment]
Ah, good find! 😊

After digging through the ancient codebase, I found out that I forgot to parse the variable names. I was treating it as a usual meter/measure's option name so I didn't consider parsing them (which I should).

Nevertheless, I have pushed a fixed version. Just enabled parsing for the variable names so there shouldn't be any breaking changes.

Thanks!
